# fly.toml file generated for shy-glitter-4369 on 2021-08-16T11:04:10-05:00

app = "shy-glitter-4369"

kill_signal = "SIGTERM"
kill_timeout = 300
services = []

[checks]

[checks.pg]
  grace_period = "30s"
  interval = "15s"
  method = "get"
  path = "/flycheck/pg"
  type = "http"
  port = 5500
  timeout = "10s"

[checks.role]
  grace_period = "30s"
  interval = "15s"
  method = "get"
  path = "/flycheck/role"
  type = "http"
  port = 5500
  timeout = "10s"

[checks.vm]
  grace_period = "1s"
  interval = "1m"
  method = "get"
  path = "/flycheck/vm"
  type = "http"
  port = 5500
  timeout = "10s"

[env]
  BACKEND_STORE = "etcdv3"
  PRIMARY_REGION = "ord"

[experimental]
  allowed_public_ports = []
  auto_rollback = false
  enable_etcd = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9187

[[mounts]]
  destination = "/data"
  encrypted = false
  source = "pg_data"
