# fly.toml file generated for wild-sun-6218 on 2021-08-16T10:20:05-05:00

app = "wild-sun-6218"

kill_signal = "SIGTERM"
kill_timeout = 300
services = []

[checks]

  [checks.pg]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    protocol = "http"
    port = 5500
    timeout = "10s"

  [checks.role]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    protocol = "http"
    port = 5500
    timeout = "10s"

  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    protocol = "http"
    port = 5500
    timeout = "10s"

[env]
  BACKEND_STORE = "etcdv3"
  PRIMARY_REGION = "ord"

[experimental]
  allowed_public_ports = []
  auto_rollback = false
  enable_etcd = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9187

[[mounts]]
  destination = "/data"
  encrypted = false
  source = "pg_data"
