# fly.toml file generated for postgres-walg-test on 2022-05-07T21:35:44+02:00

app = "postgres-walg-test"

kill_signal = "SIGTERM"
kill_timeout = 300
services = []

[checks]

  [checks.pg]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.role]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    timeout = "10s"
    type = "http"

[env]
  BACKEND_STORE = "consul"
  PRIMARY_REGION = "ams"

  ENABLE_WALG = "true"

  PGHOST = "localhost"
  PGPORT = "5432"
  PGUSER = "postgres"

  WALG_FILE_PREFIX = "/tmp/wal-g-test-data"


[experimental]
  allowed_public_ports = []
  auto_rollback = false
  enable_consul = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9187

[[mounts]]
  destination = "/data"
  source = "pg_data"
